# Generated by Django 5.0.4 on 2024-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="concept_class",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="concept",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="concept",
            name="vocabulary",
        ),
        migrations.AddField(
            model_name="concept",
            name="domain_id",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="concept",
            name="vocabulary_id",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ConceptClass",
        ),
    ]
